/**
 * Track Schema
 * 
 * Defines the logarithmic PitchTrack hierarchy and FeatureTrack abstraction
 * required for advanced DAW-like rendering and DTW analysis.
 */

/**
 * @typedef {Object} FeatureTrack
 * @property {string} type - e.g., 'confidence', 'rms', 'slope', 'curvature', 'gamak_density'
 * @property {Float32Array} data - The raw data array (length matches the midiTrack).
 * @property {number} minValue - Global minimum for normalization/rendering.
 * @property {number} maxValue - Global maximum for normalization/rendering.
 */

/**
 * @typedef {Object} LODArray
 * @property {Float32Array} min - Minimum values in the decimated chunk.
 * @property {Float32Array} max - Maximum values in the decimated chunk.
 * @property {Float32Array} avg - Average values in the decimated chunk.
 */

/**
 * Base abstract class/schema for all pitch tracks.
 * Uses fractional MIDI as the core mathematical representation.
 */
export class BasePitchTrack {
  constructor(id) {
    this.id = id || crypto.randomUUID();
    this.type = 'BasePitchTrack';
    this.isVisible = true;
    this.isMuted = false;
    
    // DSP Properties
    this.sampleRate = 100; // default 100 frames per second
    this.durationSec = 0;
    
    // LOD 0: The Raw Mathematical Data
    /** @type {Float32Array} */
    this.midiTrack = new Float32Array(0);
    
    // Extensible Feature Tracks (RMS, Confidence, Derivatives)
    /** @type {Object.<string, FeatureTrack>} */
    this.features = {};
    
    // Decimated LODs for high-performance rendering (e.g., LOD1=10fps, LOD2=1fps)
    /** @type {LODArray} */
    this.lod1 = { min: new Float32Array(0), max: new Float32Array(0), avg: new Float32Array(0) };
    /** @type {LODArray} */
    this.lod2 = { min: new Float32Array(0), max: new Float32Array(0), avg: new Float32Array(0) };
  }
}

/**
 * Represents the uploaded original audio (the 'Truth').
 */
export class ReferencePitchTrack extends BasePitchTrack {
  constructor(id) {
    super(id);
    this.type = 'ReferencePitchTrack';
    this.sourceFileId = ''; // Hash of the original audio file
  }
}

/**
 * Represents a live microphone recording from the user.
 */
export class UserPitchTrack extends BasePitchTrack {
  constructor(id) {
    super(id);
    this.type = 'UserPitchTrack';
    this.timestamp = new Date().toISOString();
  }
}

/**
 * Represents a Guru's reference layer.
 */
export class TeacherPitchTrack extends BasePitchTrack {
  constructor(id) {
    super(id);
    this.type = 'TeacherPitchTrack';
    this.teacherName = '';
  }
}

/**
 * Synthesized perfect pitch guide generated by AI/ScaleMapping.
 */
export class AIReferencePitchTrack extends BasePitchTrack {
  constructor(id) {
    super(id);
    this.type = 'AIReferencePitchTrack';
    this.generationParams = {};
  }
}
